In [1]:
import pandas as pd
a = pd.DataFrame({'A': [1, 2, 3]})

In [4]:

# Création d'un tableau 1D
arr1 = np.array([1, 2, 3, 4])

# Création d'un tableau 2D
arr2 = np.array([[1, 2], [3, 4]])

# Création d'un tableau de zéros
zeros = np.zeros((2, 3))

# Création d'un tableau de 1
ones = np.ones((3, 3))

# Tableau d'une séquence d'entiers
seq = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]

# Tableau de valeurs espacées de manière égale
linspace = np.linspace(0, 1, 5)  # [0, 0.25, 0.5, 0.75, 1]

# Opérations mathématiques sur des tableaux


In [6]:
arr = np.array([1, 2, 3, 4])

# Addition et multiplication élémentaires
arr_plus_2 = arr + 2  # [3, 4, 5, 6]
arr_times_2 = arr * 2  # [2, 4, 6, 8]

# Puissance et racine
squared = np.power(arr, 2)  # [1, 4, 9, 16]
sqrt = np.sqrt(arr)  # [1.0, 1.414, 1.732, 2.0]

# Somme et produit
arr_sum = np.sum(arr)  # 10
arr_prod = np.prod(arr)  # 24

Statistiques

In [11]:
arr = np.random.rand(100) * 100  # 100 nombres aléatoires entre 0 et 1

# Moyenne, écart type et variance
mean = np.mean(arr)  # Moyenne des valeurs
std = np.std(arr)  # Écart type
variance = np.var(arr)  # Variance

# Min et max
min_val = np.min(arr)
max_val = np.max(arr)

# Calcul des quantiles
quantiles = np.percentile(arr, [25, 50, 75])

In [12]:
mean

55.659707823987276

Comparaison de tableaux

In [25]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

# Comparaison élément par élément
comparison = np.equal(arr1, arr2)  # [True, True, True]

# Comparaison globale (les tableaux sont-ils égaux ?)
arrays_equal = np.array_equal(arr1, arr2)  # True

Gestion des valeurs manquantes

In [27]:
arr = np.array([1, 2, np.nan, 4, 5])

# Vérifier les NaN
has_nan = np.isnan(arr)  # [False, False, True, False, False]

# Remplacer les NaN
arr[np.isnan(arr)] = 0  # [1, 2, 0, 4, 5]

# Ignorer les NaN dans les calculs
mean_without_nan = np.nanmean(arr)  # Moyenne en ignorant les NaN

 Fonctions avancées

In [30]:
arr = np.array([1, 2, 3, 4, 5])

# Appliquer une fonction sur tous les éléments
exp_arr = np.exp(arr)  # exponentielle de chaque élément

# Fonctions log et trigonométriques
log_arr = np.log(arr)
sin_arr = np.sin(arr)
cos_arr = np.cos(arr)

# Intégration d'une fonction sur un tableau
integrated = np.trapz(arr)  # méthode des trapèzes

In [31]:
log_arr

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

: 

In [28]:
has_nan

array([False, False,  True, False, False])

In [26]:
arrays_equal

True

 Manipulation des tableaux

In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Transposition d'une matrice
transpose = np.transpose(arr)

# Changement de forme (reshape)
reshaped = np.reshape(arr, (1, 9))  # [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Empiler des tableaux
stacked = np.vstack([arr, arr])  # empile verticalement


In [16]:
transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Indexation et slicing

In [18]:
arr = np.array([1, 2, 3, 4, 5])

# Accéder à un élément
element = arr[2]  # 3

# Slicing (obtenir une sous-partie du tableau)
subarray = arr[1:4]  # [2, 3, 4]

# Masquage (filtrer les éléments)
mask = arr > 3
filtered = arr[mask]  # [4, 5]

Opérations sur matrices

In [20]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

# Produit matriciel
dot_product = np.dot(mat1, mat2)

# Produit élément par élément
element_wise_product = mat1 * mat2

# Déterminant d'une matrice
det = np.linalg.det(mat1)

# Inverse d'une matrice
inv = np.linalg.inv(mat1)

Génération de nombres aléatoires

In [23]:
# Nombres aléatoires entre 0 et 1
random_numbers = np.random.rand(10)

# Nombres aléatoires suivant une loi normale
normal_numbers = np.random.randn(10)

# Tirages d'une distribution binomiale
binomial_draws = np.random.binomial(n=10, p=0.5, size=10)

# Mélanger les éléments d'un tableau
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)

In [24]:
random_numbers

array([0.60618439, 0.2575616 , 0.50045427, 0.38625956, 0.04604459,
       0.99037263, 0.04640319, 0.55860814, 0.70161532, 0.14537818])

In [22]:
element_wise_product

array([[ 5, 12],
       [21, 32]])

In [19]:
filtered

array([4, 5])

In [7]:
arr_sum

10

In [5]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [2]:
a

A
0  1
1  2
2  3