Combinaison de tableaux

In [3]:
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [6]:
array = np.array([1, 4, 5, 8], float)
array = np.array([[1, 2, 3], [4, 5, 6]], float)  # a 2D array/Matrix
array

array([[1., 2., 3.],
       [4., 5., 6.]])

In [8]:
arr3 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9]])
arr3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [10]:
arr = np.array([1, 3, 5, 1, 6, 3, 1, 5, 7, 1])

print(arr == 1)
print(arr > 2)

[ True False False  True False False  True False False  True]
[False  True  True False  True  True False  True  True False]


In [17]:
z = np.random.randn(10000)  # Generate standard normals
y = np.random.binomial(10, 0.5, size=1000)    # 1,000 draws from Bin(10, 0.5)
y.mean()

5.04

In [16]:
z = np.linspace(0, 10, 5)
z

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
z = np.array([1, 2, 3])

n = len(z)
y = np.empty(n)
for i in range(n):
    y[i] = np.sin(z[i])
y

array([0.84147098, 0.90929743, 0.14112001])

In [11]:
a = np.random.randn(3)
a

array([ 1.0088264 , -1.94599329,  0.20278314])

In [9]:
arr1 = np.array([True, True, False, False])
arr2 = np.array([True, False, True, False])

print(np.logical_and(arr1, arr2))

[ True False False False]
